### ISSUE TITLE
Doesn't work with multiple network interfaces

### ISSUE THREAD

**Issue by ohmantics** [mikenemat/plum-probe#1]
A UDP broadcast to "all interfaces" really just goes over one. If the host has both ethernet and wifi, it may not find the light switches.

http://stackoverflow.com/questions/683624/udp-broadcast-on-all-interfaces covers some of it.

**Comment by ohmantics** [comment]
Looks like the netifaces package is suitable.

**Comment by mikenemat** [comment]
Thanks, this is really interesting. I can't say I've run into that issue myself, but I understand how it could be problematic. I'll take a crack at fixing it soon.

**Comment by Eno123456** [comment]
please do this quick

**Comment by mikenemat** [comment]
Resolving as a won't fix. I'd recommend enhancing it yourselves if you guys really need it to work. I don't have a test setup that matches this configuration.
